//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbanhangdienthoaididong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string LoaiSanPham { get; set; }
        public string NhaSanXuat { get; set; }
        public int SoLuong { get; set; }
        public double GiaBan { get; set; }
        public byte[] HinhAnh { get; set; }
        public string GhiChu { get; set; }
    }
}
